name: rosita
description: Flutter Rosita package
version: 0.0.1
homepage: https://github.com/flutter-rosita/flutter-rosita/tree/rosita-dev/packages/rosita

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  rosita_interface:
    path: pkg/rosita_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
